apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: {{ .Release.Name }}-deploy
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deploy
    spec:
      containers:
      - image: {{ .values.image }}:{{ .values.tag }}
        name: flaskex
        resources:
          requests:
            memory: {{ .values.resource.request.memory }}
            cpu: {{ .values.resource.request.cpu }}
        ports:
        - containerPort: {{ .values.port }}
