name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: Docker Build
      run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}"
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Docker Login
      run: docker login  -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
      
    - name: Setup KUBECONFIG
      uses: vbem/kubeconfig4sa@v1
      with:
        server:     ${{ secrets.K8S_SERVER }}
        ca-base64:  ${{ secrets.K8S_CA_BASE64 }}
        token:      ${{ secrets.K8S_SA_TOKEN }}
        namespace:  default


    - name: Deploy App
      run: helm upgrade --install myapp flaskex-chart/

    - name: delete
      run: kubectl delete pod ci-cd-pod 

     

    - name: create
      needs: delete
      run: kubectl run ci-cd-pod --image=nginx 
